### ISSUE TITLE
Feature Request: Prometheus metrics for age of oldest and newest partition

### ISSUE THREAD

**Issue by thomashargrove** [salesforce/sloop#103]
Having info about age of oldest and newest partition would let me see the duration of data in sloop, and make it easier to see when GC is kicking in for reasons other than maxLookback.  A count of total partitions would also be a nice addition.

**Comment by sana-jawad** [comment]
These metrics have been added in this PR https://github.com/salesforce/sloop/commit/e0a8d06841bb377d0757a7046ff6cc716527de80
