### ISSUE TITLE
Sloop Releases Request

### ISSUE THREAD

**Issue by acaire** [salesforce/sloop#116]
Hi, any chance you could please use releases and subsequently immutable style versioning for docker tags? I'd like to be able to pin my Sloop deployments rather than using latest.

I'm happy to submit a PR for this but would need some direction in the implementation as it requires buy-in from your side.

**Comment by sana-jawad** [comment]
Thanks @acaire we have added it in our backlog and will get to it soon.

**Comment by mallow111** [comment]
https://github.com/salesforce/sloop/pull/121/files is merged, will close this issue.

**Comment by chelomontilla** [comment]
Only latest tag can be found in https://hub.docker.com/r/sloopimage/sloop. Some more changes required?
