### ISSUE TITLE
Config file settings are not applied

### ISSUE THREAD

**Issue by rmichela** [salesforce/sloop#127]
The values in a provided config file are not being applied when Sloop boots.

I suspect this is because the config file is being [unmarshalled](https://github.com/salesforce/sloop/blob/master/pkg/sloop/server/internal/config/config.go#L178) as yaml, but the SloopConfig struct is annotated with json annotations.

**Comment by nurland** [comment]
Fixed in this PR: https://github.com/salesforce/sloop/pull/133
