### ISSUE TITLE
Support larger fonts

### ISSUE THREAD

**Issue by davidarcher** [salesforce/sloop#153]
As a DevOps engineer, I want to use Sloop to troubleshoot historical problems in Kubernetes clusters. However, I can't use it because the text next to the bars is so small as to be unreadable. Using the native browser zoom function to zoom in actually makes it smaller.

**Comment by sana-jawad** [comment]
thanks @davidarcher for reporting the issue. We have added it to our backlog and we will update this thread as soon as its done.

**Comment by venkatramreddykunta** [comment]
Hi @davidarcher, 
PR is merged [here](https://github.com/salesforce/sloop/pull/197).
CC: @sana-jawad @nurland
