### ISSUE TITLE
Can not submit search query

### ISSUE THREAD

**Issue by xcrezd** [salesforce/sloop#167]
After clicking on the "Now" button and then "submit" got the error 

![image](https://user-images.githubusercontent.com/1153266/128002882-67b1156f-89be-4a8b-98df-1b32c717aa8b.png)

**Comment by mengyaoyang11** [comment]
Hi @xcrezd, thanks for submitting the issue, could you please specify how/where you run sloop, if possible, could you please send me the link of the sloop instance you were running? Also, did you rebase with master to get the latest code? We appreciate if you can provide more detail which is needed to investigate the issue. Thanks!

**Comment by mengyaoyang11** [comment]
Also, i am wondering if you can choose the AM or PM through the date time picker, in your UI I didn't see it, ideally, it should look like this
<img width="449" alt="Screen Shot 2021-08-03 at 1 25 14 PM" src="https://user-images.githubusercontent.com/78186416/128081433-7e5ef778-bfaa-431f-8de9-6a5e2bc585f4.png">

<img width="285" alt="Screen Shot 2021-08-03 at 1 23 27 PM" src="https://user-images.githubusercontent.com/78186416/128081155-3724da61-0515-48b3-a96a-9aedc85d0e2a.png">

BTW, the `Now` button renders the current time in UTC format, so it's possible the error pops up if you select any time later than UTC now from date time picker.

**Comment by xcrezd** [comment]
You are right, I miss the AM/PM option.

I have built the docker image from the commit 
```
e86b22215520900bf060e92c60c67da9ef97ef6c (HEAD -> master, tag: v1.1, origin/master, origin/HEAD)
Author: mengyaoyang11 <78186416+mengyaoyang11@users.noreply.github.com>
Date:   Wed Jun 16 16:04:25 2021 -0700
    Present User Selected Time and Now in UTC format (#161)
```

This is the last one until now.

Also, I have these errors and messages in the Chrome developer console 
![image](https://user-images.githubusercontent.com/1153266/128178204-b2172dba-f37a-4363-8333-de61f043baf8.png)

Sloop is running on EKS 1.17v cluster, the web access is via 
`kubectl port-forward -n kube-system sloop-0 8080:8080`


Hope it's more informative.

Thanks ahead, 
Dima

**Comment by mengyaoyang11** [comment]
Can you try building sloop from source, instruction is here: https://github.com/salesforce/sloop#build-from-source and let me know how that works? Thanks

**Comment by xcrezd** [comment]
I built and run sloop locally, but still no AM/PM option

![image](https://user-images.githubusercontent.com/1153266/128310758-d2326605-c207-4b54-be1b-255515ec9344.png)

![image](https://user-images.githubusercontent.com/1153266/128310454-d0792259-4551-4c71-ad49-69f69eb211e1.png)

**Comment by xcrezd** [comment]
Chrome Developer tools
![image](https://user-images.githubusercontent.com/1153266/128311099-6055c096-949f-4297-b59c-db7a7f571067.png)

**Comment by mengyaoyang11** [comment]
The error for js files in Chrome developer console should not be a big concern, I got the error in my console but I can see the am/pm setting in my datetimepicker.  
![Screen Shot 2021-08-05 at 11 34 09 AM](https://user-images.githubusercontent.com/78186416/128402988-c931df90-307f-4124-8cf0-4bbf10525c62.png)

I would recommend switch web browser or update the chrome version. The chrome version I use is `92.0.4515.131`, can be used as a reference.

**Comment by nicolaferraro** [comment]
It does not work either on Firefox `97.0.1`.

**Comment by sana-jawad** [comment]
@nicolaferraro the fix for this issue has been checked in https://github.com/salesforce/sloop/pull/201 thanks @ryanbrainard
