### ISSUE TITLE
Can options be passed as environment variables

### ISSUE THREAD

**Issue by dchancogne** [salesforce/sloop#190]
Looking at some the options (like `badger-*`) available for Sloop it seems they have to be defined in a config file or passed as command line argument. Can they be defined via env variables? This would be useful in the container version of Sloop to be able to specify them at runtime.
Or am I missing how this can be done?

Thank you.

**Comment by sana-jawad** [comment]
@dchancogne There are three places you can specify the options currently config file, command line arguments and helm chart. Currently they are not defined via env variables. Please feel free to contribute to add this support. Thanks!

**Comment by dchancogne** [comment]
Thank you. Passing them thru the Helm chart values should work. I had somehow missed that part.
