### ISSUE TITLE
Time parsing and timezone issues

### ISSUE THREAD

**Issue by triqster** [salesforce/sloop#194]
There seems to be an issue with the date and time parsing, resulting in broken queries and therefor an empty GUI result.

Steps to reproduce:

- In the GUI enter a date and time like: 
![image](https://user-images.githubusercontent.com/5626877/143422630-56174f22-3809-48ab-838c-ccb421622537.png)

The important part here is to end with `00`

```
E1125 10:06:56.445817       1 query.go:42] computeTimeRange failed with error: parsing time "2021-11-25T08:52" as "2006-01-02T15:04:05": cannot parse "" as ":"
```
I'm  also constantly running into a already reported bug with little to no progression it seems, the query is in UTC while the "now" button and the shown time is in my current time zone (UTC +1) so I'm constantly getting errors like:
![image](https://user-images.githubusercontent.com/5626877/143422999-c97119ec-fb5c-40a0-aeac-5d63d089c1de.png)

**Comment by mengyaoyang11** [comment]
Hi @triqster thanks for reporting the issue and sorry for the late response. Could you please take a look at this discussion which reported the same issue with yours https://github.com/salesforce/sloop/issues/167. i would recommend you check your browser, ideally the date time picker should have AM/PM option for you to pick. I would recommend switch web browser or update the chrome version. The chrome version I use is 92.0.4515.131, can be used as a reference. Thanks, let me know how that works.

**Comment by mengyaoyang11** [comment]
The parsing issue you reported I attached a screenshot, its not happening on my side, again, could you please check your browser and see why the AM/PM option is missing. BTW, Some customer reported the am/pm option works only with firefox

![Screen Shot 2021-12-20 at 5 59 13 PM](https://user-images.githubusercontent.com/78186416/146857962-830e4f89-8108-4efd-b7a8-c1c435a500ea.png)
