### ISSUE TITLE
Helm chart is using deprecated API's

### ISSUE THREAD

**Issue by triqster** [salesforce/sloop#195]
The Helm chart is not compatible with a new Kubernetes release.

Kubernetes 1.19 introduced a new networking.k8s.io/v1 API for the Ingress resource. The current Ingress object has to be changed to be compatible with this new API version (v1):

- Backend configuration requires a service key and different subkeys
- A pathType is required

**Comment by sana-jawad** [comment]
@triqster thanks for the contribution. Are we good to close this issue?

**Comment by triqster** [comment]
> @triqster thanks for the contribution. Are we good to close this issue?

@sana-jawad, you're welcome this issue can be closed.
