### ISSUE TITLE
Publish HelmChart

### ISSUE THREAD

**Issue by christianknell** [salesforce/sloop#215]
Are you publishing your HelmChart to an Helm Repository? Would make it way easier to use it in production environments.

**Comment by hoerup** [comment]
Could probably be solved with 
https://github.com/marketplace/actions/helm-chart-releaser

but requires a maintainer to setup GH pages

**Comment by christianknell** [comment]
I could do this if somebody promotes me (temporally) to a maintainer. Have done this before for a couple of own helm charts: https://github.com/christianknell/helm-charts.

**Comment by pcgeek86** [comment]
The Helm Chart has not been updated in 3 years. I wouldn't trust it, especially since the README for the Helm Chart still mentions Tiller. Tiller has been deprecated for quite some time now. Helm v3 has been available since 2019.

https://helm.sh/blog/helm-v2-deprecation-timeline/

**Comment by pcgeek86** [comment]
I just tried installing the Helm Chart, and it points to an old Docker image, using the `latest` tag. The container image on Docker Hub hasn't been updated in at least a year, and the version that got installed is 0.2. See screenshot.

<img width="1387" alt="Screen Shot 2022-08-11 at 12 34 25 AM" src="https://user-images.githubusercontent.com/466713/184077195-18395432-d5d6-41ef-9008-46afb493816b.png">

### Installation Steps

- Install Helm v3 locally - platform doesn't matter (MacOS, Windows, Linux)
- Clone GitHub repository
- Change into the Helm directory: `cd ./git/sloop/helm/sloop`
- Run `helm install --create-namespace --namespace=sloop mysloop .`

**Comment by kskewes-sf** [comment]
I've just fixed permissions on the GHCR image per: https://github.com/salesforce/sloop/issues/227

We can update the Helm chart `repository:` value to `ghcr.io/salesforce/sloop`.
https://github.com/salesforce/sloop/blob/7439701d29c9d4bfc7df7795c3a8bc64fe0bb3f7/helm/sloop/values.yaml#L11

If anyone has time to update the helm chart to suit Helm V3 and the repo change I can review & merge the PR.

We should add `:latest` tag to the publishing GHA too per [metadata-action](https://github.com/docker/metadata-action#latest-tag), currently `master` is used instead.

**Comment by christianknell** [comment]
I have create a completely new version of the Helm chart in my [repository](https://github.com/christianknell/helm-charts/tree/main/charts/sloop) based on Helm v3 and up-to-date best practices. It is published in the [ArtifactHub](https://artifacthub.io/packages/helm/christianknell/sloop) as well.
