### ISSUE TITLE
Error: INSTALLATION FAILED: YAML parse error on sloop/templates/statefulset.yaml: error converting YAML to JSON: yaml: line 20: did not find expected key (New)

### ISSUE THREAD

**Issue by khaleb7** [salesforce/sloop#230]
In our environment we manage/deploy sloop via Rancher's helm.

Yesterday, the installation worked fine, using all defaults aside from namespace change to non-default.

Today after (https://github.com/salesforce/sloop/commit/2d270818818b325004fd721925b6b80d1d1d7131) went in, we installed in a different cluster and we get the following:

Error: INSTALLATION FAILED: YAML parse error on sloop/templates/statefulset.yaml: error converting YAML to JSON: yaml: line 20: did not find expected key

**Comment by sana-jawad** [comment]
Thanks @khaleb7 for reporting the issue. Can you please revert this change to unblock your self?
