### ISSUE TITLE
Running out of space in /data 

### ISSUE THREAD

**Issue by immunochomik** [salesforce/sloop#31]
How can we rotate or some such the files in /data directory?

Error that we are getting
`
E1014 07:07:58.984041       1 processing.go:38] Processing for updateKubeWatchTable failed with error Unable to write to value log file: "data/000010.vlog": write data/000010.vlog: no space left on device
badger 2019/10/14 07:07:58 ERROR: writeRequests: Unable to write to value log file: "data/000010.vlog": write data/000010.vlog: no space left on device
`

**Comment by thomashargrove** [comment]
You can set `maxDiskMb` in a config file or `max-disk-mb` on the command line.  See https://github.com/salesforce/sloop/blob/master/pkg/sloop/server/internal/config/config.go#L36

You will need to set this to something lower than the total space of the disk, so cleanup can kick in early.  I will open a feature request to set this properly in helm, and we should also explore the ability to discover the free disk space automatically.

**Comment by thomashargrove** [comment]
Turns out we had a few bugs in our GC code and some badger settings that were not ideal.  The last of the PRs related to this is https://github.com/salesforce/sloop/pull/100 Once it is merged, disk space should drop and stabilize at a reasonable volume.  Sorry for the long turn-around time.

**Comment by thomashargrove** [comment]
All known issues around disk space usage are fixed.
