### ISSUE TITLE
Sloop storeageManager should free up space if disk available space is running low

### ISSUE THREAD

**Issue by thomashargrove** [salesforce/sloop#33]
By default Sloop should clean up space if the disk free space is low even if user did not specify maxDiskMb.  We may want this behind a config switch, but for best user experience this should be on by default

**Comment by thomashargrove** [comment]
This library might come in handy: https://github.com/ricochet2200/go-disk-usage

**Comment by sana-jawad** [comment]
The issue has been resolved.
