### ISSUE TITLE
CRDs with same kind but different groups get merged together

### ISSUE THREAD

**Issue by thomashargrove** [salesforce/sloop#36]
The CRDs are only using the local resource Kind instead of the fully-qualified GroupKind. We have several CRDs that have the same Kind, but are in different Groups, so not only is it confusing in the UI because you don't know which Kind is which, but also only the last (first?) Kind with a common name is actually used.

**Comment by duke-harlan** [comment]
while creating the CRD informers, the name utilized for watching will now be `kind.group` instead of just `kind`
