### ISSUE TITLE
QUESTION: Can I run Sloop inside the cluster it's observing?

### ISSUE THREAD

**Issue by rmichela** [salesforce/sloop#7]
I'd like to try running Sloop inside the cluster being observed. Does this work?

**Comment by thomashargrove** [comment]
Absolutely.  We are working on a helm chart for Sloop that will make this easy.  We hope to get an early version out by end of next week.

You don't need too much to deploy it.  For persistent storage you can mount /data to a PVC.  For API access you may want a service account with clusterRole/clusterRoleBinding if the default service account does not have sufficient permissions.  We will include all of this in the helm chart.

**Comment by thomashargrove** [comment]
Helm chart has been added.  At the moment you need to provide your own docker image, but we are working on pre-built images.
