### ISSUE TITLE
Join Slack link is expired

### ISSUE THREAD

**Issue by alindeman** [salesforce/sloop#81]
The "Join Slack" link in [README.md](https://github.com/salesforce/sloop#contributing) appears to be expired.

<img width="614" alt="Screen Shot 2019-11-19 at 4 38 32 PM" src="https://user-images.githubusercontent.com/395621/69198894-1ee2e500-0aeb-11ea-88e9-9feb8a7e7448.png">

**Comment by nurland** [comment]
@alindeman it is fixed now, please try again.
